### ISSUE TITLE
ValueError and IndexError

### ISSUE THREAD

**Issue by JoshuaMcroberts** [nerun/AnacondaSUD#2]
Hi nerun,

I have come across an error in you code when it is run. I'm not sur eof the issue started when I made the pull request by mistake or if it was a more recent update. I am trying to debug it myself but I thought you might know the source of the problem better then I if you have a look. 

As a double check I cloned your repo to my local pc to run the code and it also isn't working.

Sorry for any trouble, I hope its a quick fix.

Error Message

```cmd
PS C:\PATH> python start.py
Traceback (most recent call last):
  File "C:\PATH \start.py", line 20, in FilesToDict
    int(i)
ValueError: invalid literal for int() with base 10: './rooms\\4'
```

During handling of the above exception, another exception occurred:

```cmd
Traceback (most recent call last):
  File "C:\PATH\start.py", line 72, in <module>
    BaseRoomsDic = FilesToDict(RoomsPath, ValidExt, 'yes')
  File "C:\PATH\start.py", line 22, in FilesToDict
    ListOfFiles.pop(n)
IndexError: pop index out of range
```

**Comment by nerun** [comment]
Maybe a Windows issue? I have cloned my repo again, and it's ok. Running on Linux here. Are you using python 3?

**Comment by nerun** [comment]
@JoshuaMcroberts, let me know if you fixed this issue. Anyway i will try to fix, i believe it's a Windows issue.

Try the new update i have made. It links all areas with bidirectional references automatically. This new way is better, because if you had 1,000 rooms you would need to add more than 1,000 lines to `start.py` to link all areas. Now it is made automatically and recursivelly.

Now I need to do this with objects spawned in rooms.

**Comment by JoshuaMcroberts** [comment]
@nerun 
Yes, it does appear to be a windows issue. 

It seems to be this section of code in FilesToDict()

### Code
```python
        for n, i in enumerate(ListOfFilesB):
            try:
                int(i)
                
            except ValueError:
                ListOfFiles.pop(n)
```

Its trying to convert a string to an int and doesn't like it, maybe we could purse out the number value from 'i' and then make that an int()

### Example Pseudo Code
```python
        for n, i in enumerate(ListOfFilesB):
            try:
                new_i = purse_number_from_string(i)  # pursing method used to split number form path
                int(new_i)
            except ValueError:
                ListOfFiles.pop(n)
```

I may have misunderstood this part of the code through

**Comment by JoshuaMcroberts** [comment]
Got it working, you might be able to make it look nicer than this but here it is.

### Old Code
```python
        for n, i in enumerate(ListOfFilesB):
            try:
                int(i)
                
            except ValueError:
                ListOfFiles.pop(n)
```

### New Code
```python
        for n, i in enumerate(ListOfFilesB):
            try:
                j = list(i)
                i = j[8]
                int(i)
                
            except ValueError:
                ListOfFiles.pop(n)
```

By the way, I'm fairly new to the world of SUD's MUD's and IF's and hope to have one up and running by Christmas. Any advice about coding them or written stroy for them is very welcome. My setting is a mordern one, I understand fantasy is a populor choice for most SUD's and MUD's.

**Comment by nerun** [comment]
Tested. Default SUD doesn't works on Windows. And your solution fixed it. BUT these changes doesn't works at Linux... Funny.

Your fix running on Linux:
```python
Traceback (most recent call last):
  File "/home/daniel/Downloads/single-user-dungeon/start.py", line 77, in <module>
    BaseRoomsDic = FilesToDict(RoomsPath, ValidExt, 'yes')
  File "/home/daniel/Downloads/single-user-dungeon/start.py", line 21, in FilesToDict
    i = j[8]
IndexError: list index out of range
```
I will study this case.

**Comment by nerun** [comment]
I have found a fast and dirt fix. Not the best way, but does works:

```python
        for n, i in enumerate(ListOfFilesB):
            try:
                if os.name in ('nt', 'dos', 'ce'):
                    j = list(i)
                    i = j[8]
                    int(i)
                else:
                    int(i)
            except ValueError:
                ListOfFiles.pop(n)
```
What it does is to ask: if on Windows, do this way, else, do the normal way.

**Comment by JoshuaMcroberts** [comment]
@nerun 

### An Issue with my solution

I didn't test my fix completely and now realise that it doesn't work for more that 9 rooms. As soon as the room numbers go into double digitals there is a problem. 

### Example
I added a room 12 to test and the ' j ' variable stores the 12 as seen below
` 
['.', '/', 'r', 'o', 'o', 'm', 's', '\\', '1', '2']
`
With your new bidirectional system it works but need to have more time to look at it.

Would it be possible to add me to the project so I can create a pull request to merge the code when I get the solution working?

**Comment by JoshuaMcroberts** [comment]
### Issue Source Found - Complete Fix
@nerun 

The main issue is with the `glob` function. 

When reading in files in **Linux** produces the floowing file path  `./rooms/1.txt` however in **Windows** it produces this file path `./rooms\\1.txt`.

When simplifying the file path name `./rooms\\` is not recognised as the `RoomsPath` varable  is set as `./rooms/` and not replaced, this causes the error. 


### Code Fix

```python
if IsRoom.lower() == "yes":
        for n, i in enumerate(ListOfFilesB):
            
            # if 'i' contains \\ switch for /
            if "\\" in i:                           # new line 1
                k = i.replace('\\', '/')            # new line 2

            a = k.replace(Path,'')                  # variable name change
            b = a.replace(Ext,'')
            ListOfFilesB[n] = b

        for n, i in enumerate(ListOfFilesB):
            try:                                    # back to origin try/except function
                    int(i)
            except ValueError:
                ListOfFiles.pop(n)
```
After looking properly at the new bidirectional system you have usedI can say I like it a lot! Great idea!

**Comment by nerun** [comment]
Very good solution! Updated. You will notice i have added and else option, otherwise this fix will not work for Linux. tested in both Windows and Linux and it now works.

```python
    if IsRoom.lower() == "yes":
        for n, i in enumerate(ListOfFilesB):
            
            # if 'i' contains \\ switch for /
            if "\\" in i:                           # new line 1
                k = i.replace('\\', '/')            # new line 2
            else:
                k = i

            a = k.replace(Path,'')                  # variable name change
            b = a.replace(Ext,'')
            ListOfFilesB[n] = b

        for n, i in enumerate(ListOfFilesB):
            try:                                    # back to origin try/except function
                    int(i)
            except ValueError:
                ListOfFiles.pop(n)
```
Closing issue.

Will add you to dev team.
